---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tca-infraforge
  namespace: argocd
  labels:
    app: tca-infraforge
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tca-infraforge/k8s-deploy-test.git  # CHANGE THIS
    targetRevision: main
    path: application-manifests/04-tca-infraforge
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
